select * from customer limit 20;

--Q1.what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

--Q2.which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)from customer);
--Q3.which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased, 
    ROUND(AVG(review_rating::numeric), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating::numeric) DESC
LIMIT 5;

--Q4.compare the average purchase amount between standard and express shipping?

select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

--Q5.does subscribed customers spend more?compare average spend and total revenue
--between subscribers and non subscribers.


 select subscription_status,
 COUNT(customer_id) as total_customers,
 ROUND(AVG(purchase_amount),2) as avg_spend,
 ROUND(SUM(purchase_amount),2) as total_revenue 
 from customer 
 group by subscription_status
 order by total_revenue, avg_spend desc;
 --Q6.which 5 products have the highest percentage of purchase which discounts applied?


 SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric 
           / COUNT(*)::numeric,
       2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7.segment customers into new returning and loyal based their total number
--of pervious purchases and show count of each segment.
WITH customers_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer 
)

SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers"
FROM customers_type
GROUP BY customer_segment;

--Q8.what are the top 3 most purchased products within the category?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;


--Q9.check whether customers with >5 purchases are more likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10.Calculate total revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;
